version: '3.7'

services:
    #--- kafka ---
    kafka:
      image: 'bitnami/kafka:latest'
      networks:
        - fires
      environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: kafka-ui
      environment:
          - KAFKA_CLUSTERS_0_NAME=local
          - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      ports: 
          - 8080:8080
      networks: 
          - fires
      depends_on:
          - kafka

    #--- Logstash ---
    logstash:
      image: fires:logstash   
      networks: 
        - fires
      environment:
        - XPACK_MONITORING_ENABLED=false
        - KAFKA_OUTPUT_BOOTSTRAP_SERVERS=kafkaserver:9092
        - KAFKA_OUTPUT_TOPIC=fires
      volumes:
        - ./logstash/pipeline/fires.conf:/usr/share/logstash/pipeline/fires.conf
        - ./logstash/pipeline/heartbeat.conf:/usr/share/logstash/pipeline/heartbeat.conf
        - ./logstash/pipeline/pipelines.yml:/usr/share/logstash/config/pipelines.yml
        - ./logstash/csv:/usr/share/logstash/csv
      depends_on:
          - kafka

volumes:
  dataframe:
  training:
  sparklibs:

networks:
  fires:
      name: fires
      driver: bridge
      ipam:
          config:
              - subnet: 10.0.100.0/24